{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-microservice
  labels:
    {{- include "python-microservice.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "python-microservice.labels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
